sudo: required
services:
  - docker
before_install:
  - docker build -t huangstanley050/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true huangstanley050/react-test npm run test -- --coverage

after_success:
  - docker build -t huang050stanley/complex-express-react-redis-postgres-client ./client
  - docker build -t huang050stanley/complex-express-react-redis-postgres-server ./server
  - docker build -t huang050stanley/complex-express-react-redis-postgres-worker ./worker
  - docker build -t huang050stanley/complex-express-react-redis-postgres-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push huangstanley050/complex-express-react-redis-postgres-client
  - docker push huangstanley050/complex-express-react-redis-postgres-server
  - docker push huangstanley050/complex-express-react-redis-postgres-worker
  - docker push huangstanley050/complex-express-react-redis-postgres-nginx
